<?php

function dosm_radmin_radmin_content($params) {
  $output = array();

  // presets
  $output['presets'] = array(
    '#type' => 'fieldset',
    '#title' => t('presets commands'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $sub_form = drupal_get_form('dosm_radmin_presets_command_form', $params);
  $output['presets']['content'] = array(
    '#type' => 'item',
    '#markup' => drupal_render($sub_form),
  );

  // console
  $output['console_command'] = array(
    '#type' => 'fieldset',
    '#title' => t('Console command'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $sub_form = drupal_get_form('dosm_radmin_console_command_form', $params);
  $output['console_command']['content'] = array(
    '#type' => 'item',
    '#markup' => drupal_render($sub_form),
  );

  return $output;
}

function dosm_radmin_console_command_form($form, &$form_state, $params) {
  $unique_id = drupal_html_id('radmin-console-command-id-');
  $form['#prefix'] = '<div id="'. $unique_id. '">';
  $form['#suffix'] = '</div>';

  // params
  $form['params'] = array(
    '#type' => 'value',
    '#value' => $params
  );

  // console command
  $form['command'] = array(
    '#type' => 'textfield',
    '#title' => t('Console command'),
    '#default_value' => '',
    '#description' => t('Send any OpenSimulator command to the simulator. example : "fcache clear" or "fcache assets" or "alert mytext"')
  );
  $form['button'] = array(
    '#type'  => 'button',
    '#name'  => 'console-command-button',
    '#value' => t('Send command'),
    '#ajax'  => array(
      'callback' => 'dosm_radmin_send_command_callback',
      'wrapper'  => $unique_id,
      'method'   => 'replace',
      'effect'   => 'fade',
    ),
  );

  $form['answer'] = array(
    '#type' => 'item',
  );
  return $form;
}

function dosm_radmin_presets_command_form($form, &$form_state, $params) {
  $unique_id = drupal_html_id('radmin-presets-command-id-');
  $form['#prefix'] = '<div id="'. $unique_id. '">';
  $form['#suffix'] = '</div>';

  // params
  $form['params'] = array(
    '#type' => 'value',
    '#value' => $params
  );

  // fcache clear
  $form['fcache_clear_button'] = array(
    '#type'  => 'button',
    '#name'  => 'fcache-clear-button',
    '#value' => t('Clear simulator cache'),
    '#ajax'  => array(
      'callback' => 'dosm_radmin_send_command_callback',
      'wrapper'  => $unique_id,
      'method'   => 'replace',
      'effect'   => 'fade',
    ),
  );

  // fcache assets
  $form['fcache_assets_button'] = array(
    '#type'  => 'button',
    '#name'  => 'fcache-assets-button',
    '#value' => t('Preload assets in cache'),
    '#ajax'  => array(
      'callback' => 'dosm_radmin_send_command_callback',
      'wrapper'  => $unique_id,
      'method'   => 'replace',
      'effect'   => 'fade',
    ),
  );

  $form['answer'] = array(
    '#type' => 'item',
  );
  return $form;
}

function dosm_radmin_send_command_callback($form, &$form_state) {
  //return $form_state['clicked_button']['#name'];
  $params = array(
    'url' => $form_state['values']['params']['url'],
    'port' => $form_state['values']['params']['port'],
    'path' => '/',
    'params' => array(
      'struct' => array(
        'password' => htmlspecialchars($form_state['values']['params']['password']),
      )
    )
  );
  switch ($form_state['clicked_button']['#name']) {
    // console command
    case 'console-command-button':
      if ($form_state['values']['command'] == "") {
        $form['answer']['#markup'] = t('Please, enter a command to send.');
        return $form;
      }
      $params['method'] = 'admin_console_command';
      $params['params']['struct']['command'] = $form_state['values']['command'];
      break;
    // fcache clear
    case 'fcache-clear-button':
      $params['method'] = 'admin_console_command';
      $params['params']['struct']['command'] = 'fcache clear';
      break;
    // fcache assets
    case 'fcache-assets-button':
      $params['method'] = 'admin_console_command';
      $params['params']['struct']['command'] = 'fcache assets';
      break;
  }
  $response = dosm_xmlrpc_call($params);
  if ($response['success']) {
    $form['answer']['#markup'] = '<div class="messages status success"><pre>'. print_r($response, true). '</pre></div>';
  }
  else {
    if ($response['message'] == 'No answer') {
      $form['answer']['#markup'] =  '<div class="messages warning">'. t('The command was sent.'). '</div>';
    }
    else {
      $form['answer']['#markup'] =  '<div class="messages error">'. t('The system is not responding. Error code : @error', array('@error'=>$response['message'])). '</div>';
    }
  }
  return $form;
}
