<?php

/**
 * Implements hook_node_view.
 */
function dosm_radmin_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'dosm_simulator') {
    if (dosm_radmin_can_see_simulator_form($node)) {
      $machine = $node->field_dosm_machine[LANGUAGE_NONE][0]['entity'];
      $config = array(
        'url' => $machine->field_dosm_machine_url[LANGUAGE_NONE][0]['value'],
        'port' => $node->field_dosm_sim_radmin_port[LANGUAGE_NONE][0]['value'],
        'password' => $node->field_dosm_sim_radmin_password[LANGUAGE_NONE][0]['value'],
      );

      $node->content['dosm_radmin_machine'] = drupal_get_form('dosm_radmin_simulator_form', $node);
      //$node->content['dosm_radmin_commands'] = drupal_get_form('dosm_radmin_radmin_form', $node);
      $node->content['dosm_radmin_radmin'] = drupal_get_form('dosm_radmin_console_command_form', $config);
    }
  }
}

function dosm_radmin_can_see_simulator_form($node, $account=null) {
  global $user;
  if (dosm_is_manager($user->uid, $node) || $user->uid == 1) {
    return TRUE;
  }
  return FALSE;
}

function dosm_radmin_simulator_form($form, &$form_state, $node) {
  $machine = $node->field_dosm_machine[LANGUAGE_NONE][0]['entity'];
  $url = $machine->field_dosm_machine_url[LANGUAGE_NONE][0]['value'];
  $port = $machine->field_dosm_machine_port[LANGUAGE_NONE][0]['value'];
  $path = $machine->field_dosm_machine_path[LANGUAGE_NONE][0]['value'];
  $params = array(
    'url' => $url,
    'port' => $port,
    'path' => $path,
    'method' => 'get_sim',
    'params' => array(
      'password' => $machine->field_dosm_machine_password[LANGUAGE_NONE][0]['value'],
      'sim_path' => $node->field_dosm_sim_path[LANGUAGE_NONE][0]['value'],
    )
  );
  $response = dosm_xmlrpc_call($params);

  if ($response['success'] && $response['data']['success']) {
    $sim = $response['data']['sim'];
    $params['sim'] = $sim;
    $params['sim_user_id'] = 0;
    $params['sim_id'] = 0;
    $sub_form = drupal_get_form('dosm_sysadmin_sim_form', $sim, $params);
    $form['sim'] = array(
      '#type' => 'item',
      '#markup' => drupal_render($sub_form)
    );
  }
  return $form;
}

function dosm_radmin_radmin_form($form, &$form_state, $node) {
  $form['radmin'] = array(
    '#type' => 'fieldset',
    '#title' => t('Internal'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  // build the config
  $machine = $node->field_dosm_machine[LANGUAGE_NONE][0]['entity'];
  $params = array(
    'url' => $machine->field_dosm_machine_url[LANGUAGE_NONE][0]['value'],
    'port' => $node->field_dosm_sim_radmin_port[LANGUAGE_NONE][0]['value'],
    'password' => $node->field_dosm_sim_radmin_password[LANGUAGE_NONE][0]['value'],
  );
  $sub_form = drupal_get_form('dosm_radmin_console_command_form', $params);
  $form['radmin']['console_command'] = array(
    '#type' => 'item',
    '#title' => "aaa",
    '#markup' => drupal_render($sub_form),
  );
  return $form;
}

function dosm_radmin_console_command_form($form, &$form_state, $params) {
  $unique_id = drupal_html_id('radmin-console-command-id-');
  $form['#prefix'] = '<div id="'. $unique_id. '">';
  $form['#suffix'] = '</div>';

  // params
  $form['params'] = array(
    '#type' => 'value',
    '#value' => $params
  );

  // console command
  $form['console_command'] = array(
    '#type' => 'fieldset',
    '#title' => t('Console command'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE
  );
  $form['console_command']['command'] = array(
    '#type' => 'textfield',
    '#title' => t('Console command'),
    '#default_value' => ''
  );
  $form['console_command']['button'] = array(
    '#type'  => 'button',
    '#name'  => 'console-command-button',
    '#value' => t('Send any command to the simulator'),
    '#ajax'  => array(
      'callback' => 'dosm_radmin_send_command_callback',
      'wrapper'  => $unique_id,
      'method'   => 'replace',
      'effect'   => 'fade',
    ),
  );

  $form['console_command']['answer'] = array(
    '#type' => 'item',
  );
  return $form;
}

function dosm_radmin_send_command_callback($form, &$form_state) {
  $params = array(
    'url' => $form_state['values']['params']['url'],
    'port' => $form_state['values']['params']['port'],
    'path' => '/',
    'params' => array(
      'struct' => array(
        'password' => htmlspecialchars($form_state['values']['params']['password']),
      )
    )
  );
  switch ($form_state['clicked_button']['#name']) {
  // console command
  case 'console-command-button':
    if ($form_state['values']['console_command']['command'] == "") {
      $form['console_command']['answer']['#markup'] = t('Please, enter a command to send.');
      return $form;
    }
    $params['method'] = 'admin_console_command';
    $params['params']['struct']['command'] = $form_state['values']['console_command']['command'];
    break;
  }
  $response = dosm_xmlrpc_call($params);
  if ($response['success']) {
    $form['console_command']['answer']['#markup'] = '<div class="success"><pre>'. print_r($response, true). '</pre></div>';
  }
  else {
    $form['console_command']['answer']['#markup'] =  '<div class="messages error">'. t('The system is not responding. Error code : @error', array('@error'=>$response['message'])). '</div>';
  }
  return $form;
}
